//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.24 at 05:18:48 PM IST 
//


package com.howtodoinjava.xml.feature;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FeatureDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="featureEntity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="featureId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="featureDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="featureAbbr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="featureAppId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="featureValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="featureEFD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="featureEXD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="featureUPD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureDetailType", propOrder = {
    "featureEntity",
    "featureId",
    "featureDescription",
    "featureAbbr",
    "featureAppId",
    "featureValue",
    "featureEFD",
    "featureEXD",
    "featureUPD"
})
public class FeatureDetailType {

    @XmlElement(required = true)
    protected String featureEntity;
    @XmlElement(required = true)
    protected String featureId;
    @XmlElement(required = true)
    protected String featureDescription;
    @XmlElement(required = true)
    protected String featureAbbr;
    @XmlElement(required = true)
    protected String featureAppId;
    @XmlElement(required = true)
    protected String featureValue;
    @XmlElement(required = true)
    protected String featureEFD;
    @XmlElement(required = true)
    protected String featureEXD;
    @XmlElement(required = true)
    protected String featureUPD;

    /**
     * Gets the value of the featureEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureEntity() {
        return featureEntity;
    }

    /**
     * Sets the value of the featureEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureEntity(String value) {
        this.featureEntity = value;
    }

    /**
     * Gets the value of the featureId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureId() {
        return featureId;
    }

    /**
     * Sets the value of the featureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureId(String value) {
        this.featureId = value;
    }

    /**
     * Gets the value of the featureDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureDescription() {
        return featureDescription;
    }

    /**
     * Sets the value of the featureDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureDescription(String value) {
        this.featureDescription = value;
    }

    /**
     * Gets the value of the featureAbbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureAbbr() {
        return featureAbbr;
    }

    /**
     * Sets the value of the featureAbbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureAbbr(String value) {
        this.featureAbbr = value;
    }

    /**
     * Gets the value of the featureAppId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureAppId() {
        return featureAppId;
    }

    /**
     * Sets the value of the featureAppId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureAppId(String value) {
        this.featureAppId = value;
    }

    /**
     * Gets the value of the featureValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureValue() {
        return featureValue;
    }

    /**
     * Sets the value of the featureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureValue(String value) {
        this.featureValue = value;
    }

    /**
     * Gets the value of the featureEFD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureEFD() {
        return featureEFD;
    }

    /**
     * Sets the value of the featureEFD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureEFD(String value) {
        this.featureEFD = value;
    }

    /**
     * Gets the value of the featureEXD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureEXD() {
        return featureEXD;
    }

    /**
     * Sets the value of the featureEXD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureEXD(String value) {
        this.featureEXD = value;
    }

    /**
     * Gets the value of the featureUPD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureUPD() {
        return featureUPD;
    }

    /**
     * Sets the value of the featureUPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureUPD(String value) {
        this.featureUPD = value;
    }

}
