//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.24 at 05:18:48 PM IST 
//


package com.howtodoinjava.xml.feature;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetFeatureDetailRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetFeatureDetailRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dates" type="{http://www.howtodoinjava.com/xml/feature}DatesType" minOccurs="0"/>
 *         &lt;element name="entities" type="{http://www.howtodoinjava.com/xml/feature}EntitiesType" minOccurs="0"/>
 *         &lt;element name="features" type="{http://www.howtodoinjava.com/xml/feature}FeaturesType" minOccurs="0"/>
 *         &lt;element name="applications" type="{http://www.howtodoinjava.com/xml/feature}ApplicationsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetFeatureDetailRequestType", propOrder = {
    "dates",
    "entities",
    "features",
    "applications"
})
public class GetFeatureDetailRequestType {

    protected DatesType dates;
    protected EntitiesType entities;
    protected FeaturesType features;
    protected ApplicationsType applications;

    /**
     * Gets the value of the dates property.
     * 
     * @return
     *     possible object is
     *     {@link DatesType }
     *     
     */
    public DatesType getDates() {
        return dates;
    }

    /**
     * Sets the value of the dates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatesType }
     *     
     */
    public void setDates(DatesType value) {
        this.dates = value;
    }

    /**
     * Gets the value of the entities property.
     * 
     * @return
     *     possible object is
     *     {@link EntitiesType }
     *     
     */
    public EntitiesType getEntities() {
        return entities;
    }

    /**
     * Sets the value of the entities property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntitiesType }
     *     
     */
    public void setEntities(EntitiesType value) {
        this.entities = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link FeaturesType }
     *     
     */
    public FeaturesType getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeaturesType }
     *     
     */
    public void setFeatures(FeaturesType value) {
        this.features = value;
    }

    /**
     * Gets the value of the applications property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationsType }
     *     
     */
    public ApplicationsType getApplications() {
        return applications;
    }

    /**
     * Sets the value of the applications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationsType }
     *     
     */
    public void setApplications(ApplicationsType value) {
        this.applications = value;
    }

}
