//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.24 at 05:18:48 PM IST 
//


package com.howtodoinjava.xml.feature;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.howtodoinjava.xml.feature package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetFeatureDetailRequest_QNAME = new QName("http://www.howtodoinjava.com/xml/feature", "getFeatureDetailRequest");
    private final static QName _GetFeatureDetailResponse_QNAME = new QName("http://www.howtodoinjava.com/xml/feature", "getFeatureDetailResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.howtodoinjava.xml.feature
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetFeatureDetailResponseType }
     * 
     */
    public GetFeatureDetailResponseType createGetFeatureDetailResponseType() {
        return new GetFeatureDetailResponseType();
    }

    /**
     * Create an instance of {@link GetFeatureDetailRequestType }
     * 
     */
    public GetFeatureDetailRequestType createGetFeatureDetailRequestType() {
        return new GetFeatureDetailRequestType();
    }

    /**
     * Create an instance of {@link EntitiesType }
     * 
     */
    public EntitiesType createEntitiesType() {
        return new EntitiesType();
    }

    /**
     * Create an instance of {@link ApplicationsType }
     * 
     */
    public ApplicationsType createApplicationsType() {
        return new ApplicationsType();
    }

    /**
     * Create an instance of {@link FeatureDetailType }
     * 
     */
    public FeatureDetailType createFeatureDetailType() {
        return new FeatureDetailType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link DatesType }
     * 
     */
    public DatesType createDatesType() {
        return new DatesType();
    }

    /**
     * Create an instance of {@link FeaturesType }
     * 
     */
    public FeaturesType createFeaturesType() {
        return new FeaturesType();
    }

    /**
     * Create an instance of {@link FeatureDetailsType }
     * 
     */
    public FeatureDetailsType createFeatureDetailsType() {
        return new FeatureDetailsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetFeatureDetailRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.howtodoinjava.com/xml/feature", name = "getFeatureDetailRequest")
    public JAXBElement<GetFeatureDetailRequestType> createGetFeatureDetailRequest(GetFeatureDetailRequestType value) {
        return new JAXBElement<GetFeatureDetailRequestType>(_GetFeatureDetailRequest_QNAME, GetFeatureDetailRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetFeatureDetailResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.howtodoinjava.com/xml/feature", name = "getFeatureDetailResponse")
    public JAXBElement<GetFeatureDetailResponseType> createGetFeatureDetailResponse(GetFeatureDetailResponseType value) {
        return new JAXBElement<GetFeatureDetailResponseType>(_GetFeatureDetailResponse_QNAME, GetFeatureDetailResponseType.class, null, value);
    }

}
